/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Model;

import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author paj13suu
 */
public class Calender extends javax.swing.JFrame {
    Connection con;
    PreparedStatement stmt;
    ResultSet rs;
    int USER_ID;
    String USER_NAME = "DANLING";
    String mod;
    String name;
    String start;
    String end;
    String date;
    String room;
    String complete = "";
    
    public Calender() throws SQLException {
        initComponents();
        DoConnect();
        updateEvents();
    }
    
     public void DoConnect() {
        try {
            String host = "jdbc:derby://localhost:1527/software1";
            String uName = "software";
            String uPass = "engineers";
            con = DriverManager.getConnection(host, uName, uPass);
        } catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }
    public void updateEvents() throws SQLException{
        stmt = con.prepareStatement("select * from SOFTWARE.USERPROFILE WHERE USERNAME =   ?  ");
        stmt.setString(1, USER_NAME);
        rs = stmt.executeQuery();
        while (rs.next()) {
            USER_ID = rs.getInt("USER_ID");
        }
        
        stmt = con.prepareStatement("SELECT USERPROFILE.USER_ID, TIMETABLE.MODULE_CODE, TIMETABLE.TT_NAME, TIMETABLE.STARTTIME, TIMETABLE.ENDTIME, TIMETABLE.TT_DATE, TIMETABLE.ROOM\n" +
                                    "FROM TIMETABLE\n" +
                                    "INNER JOIN USERPROFILE\n" +
                                    "ON USERPROFILE.MODULE1=TIMETABLE.MODULE_CODE AND USERPROFILE.MODULE2=TIMETABLE.MODULE_CODE\n" +
                                    "AND USERPROFILE.MODULE3=TIMETABLE.MODULE_CODE AND USERPROFILE.MODULE4=TIMETABLE.MODULE_CODE\n" +
                                    "AND USERPROFILE.MODULE5=TIMETABLE.MODULE_CODE AND USERPROFILE.MODULE6=TIMETABLE.MODULE_CODE\n" +
                                    "WHERE USERPROFILE.USER_ID = ?;");
        stmt.setInt(1, USER_ID);
        rs = stmt.executeQuery();
        while (rs.next()) {
            mod = rs.getString("MODULE_CODE");
            name = rs.getString("TT_NAME");
            start = rs.getString("STARTTIME");
            end = rs.getString("ENDTIME");
            date = rs.getString("TT_DATE");
            room = rs.getString("ROOM");
            complete += "Module: " + mod + " | Name: " + name +" | Start: " + start +" | End: " + end +" | Date: " + date +" | Room: " + room + "\n";
        }
        events.setText(complete);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        events = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        events.setColumns(20);
        events.setRows(5);
        jScrollPane2.setViewportView(events);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Calender().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Calender.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea events;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
